### ISSUE TITLE
Possible VDF Issue

### ISSUE THREAD

**Issue by duffyknight** [MASGAU/MASGAU#107]
I am getting this error message on start up for my pc pretty regularly.
WHT THE HELL

   at VDF.NestedElement..ctor(Queue`1 read) in E:\GIT\MASGAU\Libs\VDF\NestedElement.cs:line 31
   at VDF.NestedElement..ctor(Queue`1 read) in E:\GIT\MASGAU\Libs\VDF\NestedElement.cs:line 42
   at VDF.NestedElement..ctor(Queue`1 read) in E:\GIT\MASGAU\Libs\VDF\NestedElement.cs:line 42
   at VDF.NestedElement..ctor(Queue`1 read) in E:\GIT\MASGAU\Libs\VDF\NestedElement.cs:line 42
   at VDF.NestedElement..ctor(Queue`1 read) in E:\GIT\MASGAU\Libs\VDF\NestedElement.cs:line 42
   at VDF.NestedElement..ctor(Queue`1 read) in E:\GIT\MASGAU\Libs\VDF\NestedElement.cs:line 42
   at VDF.NestedElementFile..ctor(String file_name) in E:\GIT\MASGAU\Libs\VDF\NestedElementFile.cs:line 20
   at VDF.VDFFile..ctor(String file_name) in E:\GIT\MASGAU\Libs\VDF\VDFFile.cs:line 8
   at VDF.SteamConfigFile..ctor(String file_name) in E:\GIT\MASGAU\Libs\VDF\SteamConfigFile.cs:line 8
   at MASGAU.Location.SteamLocationHandler.resetSteamPath() in E:\GIT\MASGAU\MASGAU.Windows\Location\SteamLocationHandler.cs:line 67
   at MASGAU.Location.ASteamLocationHandler..ctor() in E:\GIT\MASGAU\MASGAU.Common\Location\ASteamLocationHandler.cs:line 14
   at MASGAU.Location.SteamLocationHandler..ctor() in E:\GIT\MASGAU\MASGAU.Windows\Location\SteamLocationHandler.cs:line 10
   at MASGAU.Location.LocationsHandler.setupSteamHandler() in E:\GIT\MASGAU\MASGAU.Windows\Location\LocationsHandler.cs:line 10
   at MASGAU.Location.ALocationsHandler.setup() in E:\GIT\MASGAU\MASGAU.Common\Location\ALocationsHandler.cs:line 53
   at MASGAU.AProgramHandler.doWork(Object sender, DoWorkEventArgs e) in E:\GIT\MASGAU\MASGAU.Common\AProgramHandler.cs:line 50
   at MASGAU.Main.MainProgramHandler.doWork(Object sender, DoWorkEventArgs e) in E:\GIT\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 28
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by sanmadjack** [comment]
This only happens when Steam is not logged in. If you log into steam, or save your credentials on startup, this error doesn't happen.

**Comment by AdmiringWorm** [comment]
@sanmadjack. I know this is an old issue, but do you remember if you had fixed this in the v1.0.8 branch?

**Comment by sanmadjack** [comment]
I never got around to it, no.

**Comment by AdmiringWorm** [comment]
damn, I was hoping you did. I was trying to reproduce it and wasn't able to. I'll see if I can't get some time to work on it in the near future.

**Comment by AdmiringWorm** [comment]
@sanmadjack so I was able to find and fix this issue, I've put up a P.R. for the VDF library:
https://github.com/sanmadjack/VDF/pull/1
