### ISSUE TITLE
NullReferenceException on MASGAU Beta 10.0 startup

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#41]
On startup of the MASGAU Beta 10.0 I got a NullReferenceException.

```
16.08.2012 23:27:50 - STRING MainWindow NOT FOUND
16.08.2012 23:27:50 - STRING UpdateAvailable NOT FOUND
16.08.2012 23:27:50 - STRING ChangeSyncFolder NOT FOUND
16.08.2012 23:27:50 - STRING OpenSyncFolder NOT FOUND
16.08.2012 23:27:50 - STRING SyncFolder NOT FOUND
16.08.2012 23:27:50 - STRING GameCount NOT FOUND
16.08.2012 23:27:50 - STRING Ready NOT FOUND
```

```
16.08.2012 23:27:54 - Error on program startup
16.08.2012 23:27:54 - 16.08.2012 23:27:54 - An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at MASGAU.Main.MainWindowNew.update_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in Y:\Desktop\Projects\MASGAU\MASGAU.Main.WPF\MainWindowUpdate.cs:line 45
   at System.ComponentModel.RunWorkerCompletedEventHandler.Invoke(Object sender, RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

16.08.2012 23:27:54 - 16.08.2012 23:27:54 - Object reference not set to an instance of an object.   at MASGAU.Update.UpdatesHandler.checkUpdates(Boolean updater_program, Boolean suppress_no_update_message) in Y:\Desktop\Projects\MASGAU\Masgau\Update\UpdatesHandler.cs:line 145
   at MASGAU.Main.MainWindowNew.update_DoWork(Object sender, DoWorkEventArgs e) in Y:\Desktop\Projects\MASGAU\MASGAU.Main.WPF\MainWindowUpdate.cs:line 41
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

```
16.08.2012 23:27:55 - 16.08.2012 23:27:55 - An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at MASGAU.Main.MainWindowNew.update_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in Y:\Desktop\Projects\MASGAU\MASGAU.Main.WPF\MainWindowUpdate.cs:line 45
   at System.ComponentModel.RunWorkerCompletedEventHandler.Invoke(Object sender, RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at MASGAU.Program.Main() in Y:\Desktop\Projects\MASGAU\MASGAU.Main.WPF\Program.cs:line 17

16.08.2012 23:27:55 - 16.08.2012 23:27:55 - Object reference not set to an instance of an object.   at MASGAU.Update.UpdatesHandler.checkUpdates(Boolean updater_program, Boolean suppress_no_update_message) in Y:\Desktop\Projects\MASGAU\Masgau\Update\UpdatesHandler.cs:line 145
   at MASGAU.Main.MainWindowNew.update_DoWork(Object sender, DoWorkEventArgs e) in Y:\Desktop\Projects\MASGAU\MASGAU.Main.WPF\MainWindowUpdate.cs:line 41
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by sanmadjack** [comment]
Not sure where this bug was fixed, but the latest builds don't have it anymore.
