### ISSUE TITLE
Masgau fails poorly with malformed archive.

### ISSUE THREAD

**Issue by OranguTech** [MASGAU/MASGAU#71]
Whilst scanning/reading through my save archive, MASGAU give an error on a particular file (that I have not been spent the time to split-test, a quick pass w/ Procmon was inconlusive.)

Popup window (title not visible, but windows reports it as "Translator Error".

"The string ArchiveMissingData could not be found"

> Exception Information:

<pre>

ArchiveMissingData

   at MASGAU.Archive..ctor(FileInfo archive) in Y:\Desktop\Projects\MASGAU\MASGAU.Common\Archive\Archive.cs:line 190
   at MASGAU.Archives.DetectBackups() in Y:\Desktop\Projects\MASGAU\MASGAU.Common\Archive\Archives.cs:line 56

</pre>

Click "Send Report" and get another popup that says simply: 
'WTF?'
(Again no title, seems to be system.exception - I'm guessing this is your catch-all error handler. Perhaps you could add a display of which file is currently being scanned?)

> Exception Information:

<pre>
   at Email.WPF.EmailButton.checkEmails() in Y:\Desktop\Projects\MASGAU\Libs\Email.WPF\EmailButton.xaml.cs:line 82
   at Email.WPF.EmailButton.button_Click(Object sender, RoutedEventArgs e) in Y:\Desktop\Projects\MASGAU\Libs\Email.WPF\EmailButton.xaml.cs:line 37
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
</pre>

Closing both windows, it seems to ignore the error (reading a bad archive file?) and get on with life.

**Comment by OranguTech** [comment]
I'm a dork, didn't take long to find the offending archive. Would you like me to send it? (Black Mesa Source, 24Megs)

Edit-Edit: 7zip can't open it, so obviously a corrupted .7zip.

**Comment by sanmadjack** [comment]
I'd like to see it anyway, e-mail it to me? sanmadjack@masgau.org

**Comment by sanmadjack** [comment]
This shouldn't be hard to fix, I'm pretty sure I know what's going on here.

**Comment by sanmadjack** [comment]
The string ArchiveMissingData  was missing from the English file. I've added it, and this should be present in the next release.
