### ISSUE TITLE
"startIndex cannot be larger than length of string."

### ISSUE THREAD

**Issue by OranguTech** [MASGAU/MASGAU#75]
Wow, I get all the fun ones. I get that error now on launch:

startIndex cannot be larger than length of string.
Parameter name: startIndex

   at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
   at System.String.Substring(Int32 startIndex)
   at MASGAU.Location.ALocationHandler.interpretPath(String interpret_me) in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Location\ALocationHandler.cs:line 184
   at MASGAU.Location.ALocationsHandler.interpretPath(String[] interpret_me) in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Location\ALocationsHandler.cs:line 178
   at MASGAU.GameEntry.Detect() in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\GameEntry.cs:line 276
   at MASGAU.Games.detectGames(List`1 these_games) in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 297
   at MASGAU.Main.MainProgramHandler.detectGames() in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 42
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Clicking "Send Report" generates the "WTF?" exception.:

WTF?

   at Email.WPF.EmailButton.checkEmails() in C:\Users\Matthew\Desktop\MASGAU\Libs\Email.WPF\EmailButton.xaml.cs:line 82
   at Email.WPF.EmailButton.button_Click(Object sender, RoutedEventArgs e) in C:\Users\Matthew\Desktop\MASGAU\Libs\Email.WPF\EmailButton.xaml.cs:line 37
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by sanmadjack** [comment]
Congrats, you triggered an exception that should have been technically impossible to trigger. I need to get you an award or something.

**Comment by OranguTech** [comment]
It's a gift. (Do you want a copy of a log or, if applicable, track down the offending backup file? (If that's the 2nd corrupt file then I got some weird juju...)

**Comment by sanmadjack** [comment]
I should be able to figure it out from this stack trace, I just need to find the time to work on it.

**Comment by sanmadjack** [comment]
Are you still getting this error?

**Comment by sanmadjack** [comment]
I've got a possible fix for this error, but I need to confirm it. Do you still get the error?

**Comment by OranguTech** [comment]
Sorry I never got back to you, but dont think i can answer that - some
combination of moving, migration, updating or resyncing fixed it. Or it was
on my desktop that has been offline for 2 months...

**Comment by sanmadjack** [comment]
Heh. Well, I'm pretty sure this fixes the issue, so I'll go ahead and push the issue. Please open a new issue if ti re-surfaces.

**Comment by sanmadjack** [comment]
Dplicate of #77
