### ISSUE TITLE
A (new?) startup crash for me.

### ISSUE THREAD

**Issue by OranguTech** [MASGAU/MASGAU#96]
Only occurs on one machine:

Attempted to perform an unauthorized operation.

Exception Information:

```
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath)
   at System.IO.DirectoryInfo.SetAccessControl(DirectorySecurity directorySecurity)
   at MASGAU.Game.GameXmlFiles..ctor() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\GameXmlFiles.cs:line 99
   at MASGAU.Games.loadXml() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 206
   at MASGAU.Games.detectGames(List`1 these_games) in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 261
   at MASGAU.Games.detectGames() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Game\Games.cs:line 236
   at MASGAU.Main.MainProgramHandler.detectGames() in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 43
   at MASGAU.Main.MainProgramHandler.doWork(Object sender, DoWorkEventArgs e) in c:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 38
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```

I can click "send report" and it appears to have sent.
There is a small, blank masgau window, maybe 2" x 1", separate from the main window.

 I haven't done much troubleshooting yet - like all my systems, MASGAU 1.0.6 on Win 7x64, backup folder is SkyDrive sub-folder.

**Comment by sanmadjack** [comment]
Does this occur every time you try to start it?

**Comment by sanmadjack** [comment]
What is the computer's primary language?

**Comment by OranguTech** [comment]
Every time, been that way over a couple weeks now over multiple restarts. English. Where is the masgau pref file again? I tried re-installing, no help.

**Comment by sanmadjack** [comment]
The preferences should be in AppData\masgau or something like that.

**Comment by sanmadjack** [comment]
This here is a test build that may or may not resolve this: 

https://drive.google.com/file/d/0By2Mfv6zO9Ska1ZIWnM0UGxzcVU/edit?usp=sharing

**Comment by OranguTech** [comment]
Test build shows same symptoms. Interestingly running the all-users mode loads without complaint. I guess I'll run with that for now, but happy to help w/ any other troubleshooting steps.

**Comment by sanmadjack** [comment]
I'll try to poke around this error this weekend.

**Comment by sanmadjack** [comment]
Some extra data...

Application Info:
Entry Assembly:
Codebase: file:///C:/Program Files/MASGAU/MASGAU.exe
Full Name: MASGAU, Version=1.0.6.33515, Culture=neutral, PublicKeyToken=null
Image Runtime Version: v4.0.30319
Location: C:\Program Files\MASGAU\MASGAU.exe
Version: 1.0.6.0

Executing Assembly:
Codebase: file:///C:/Program Files/MASGAU/MVC.DLL
Full Name: MVC, Version=1.0.0.33510, Culture=neutral, PublicKeyToken=fca8a6abfa01e165
Image Runtime Version: v4.0.30319
Location: C:\Program Files\MASGAU\MVC.dll
Version: 1.0.0.0

**Comment by sanmadjack** [comment]
The code in question here resets the permissions on the xml data folder, mostly to make sure that the update system is capable of updating the XML files. Could you check what the permissions are like in your c:\ProgramData\masgau folder?

**Comment by OranguTech** [comment]
Ah, short answer: Permissions problem. Running single-user mode as admin works. User had no special permissions on \program data\masgau\ Adding write perms did not solve it, giving full control did.

That weird, blank, un-selectable secondary window is still there though. Haunting and taunting me. :smile: 

Running Process Monitor and filtering on just file access for masgau.exe didn't help particularly, but I have the PML file if that would be helpful.

As for the pre-"fixed" permissions, I suppose you mean something like: (Username has been replaced by "Bob_or_Alice")

```
c:\ProgramData>icacls masgau
masgau Everyone:(OI)(CI)(IO)(F)
       NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
       BUILTIN\Administrators:(I)(OI)(CI)(F)
       CREATOR OWNER:(I)(OI)(CI)(IO)(F)
       BUILTIN\Users:(I)(OI)(CI)(RX)
       BUILTIN\Users:(I)(CI)(WD,AD,WEA,WA)

====
c:\ProgramData>icacls masgau\*
masgau\a.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\b.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\c.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\custom.xml Everyone:(I)(F)
                  NT AUTHORITY\SYSTEM:(I)(F)
                  BUILTIN\Administrators:(I)(F)
                  BUILTIN\Users:(I)(RX)

masgau\d.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\deprecated.xml Everyone:(F)
                      NT AUTHORITY\SYSTEM:(F)
                      BUILTIN\Administrators:(F
                      OU\Bob_or_Alice:(F)

masgau\e.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\f.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\g.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\GameSaveInfo20.xsd Everyone:(I)(F)
                          NT AUTHORITY\SYSTEM:(
                          BUILTIN\Administrator
                          BUILTIN\Users:(I)(RX)

masgau\h.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\i.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\j.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\k.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\l.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\m.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\n.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\numeric.xml Everyone:(F)
                   NT AUTHORITY\SYSTEM:(F)
                   BUILTIN\Administrators:(F)
                   OU\Bob_or_Alice:(F)

masgau\o.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\p.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\q.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\r.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\s.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\system.xml Everyone:(F)
                  NT AUTHORITY\SYSTEM:(F)
                  BUILTIN\Administrators:(F)
                  OU\Bob_or_Alice:(F)

masgau\t.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\u.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\v.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\w.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\x.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\y.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)

masgau\z.xml Everyone:(F)
             NT AUTHORITY\SYSTEM:(F)
             BUILTIN\Administrators:(F)
             OU\Bob_or_Alice:(F)
```

**Comment by sanmadjack** [comment]
Mind posting a screen of that second window?

**Comment by OranguTech** [comment]
Little window in the top left:

![masgau_ghostwindow](https://f.cloud.github.com/assets/1691149/2100658/d9d80444-8f4a-11e3-8ef4-5dabe075e9ec.PNG)

Note also that it shows up as a second, blank item in the taskbar, which is the only way to select (put focus on) that window. (Not that you can do anything with it still.)
![masgau_ghosttaskbar](https://f.cloud.github.com/assets/1691149/2100711/69b36cf2-8f4b-11e3-9d41-935d73fc6e86.PNG)

**Comment by OranguTech** [comment]
Just tested w/ the 1.0.8 debug build you posted for PlottingCreeper, but no difference. (And debug startup stuff goes by too fast - probably should dump it to stdout, er, a log of some sort. :)

**Comment by OranguTech** [comment]
So - do you want me to close this one and re-open the window bug?

**Comment by sanmadjack** [comment]
Yeah, that's a good idea.

**Comment by OranguTech** [comment]
Closing due to permissions work-around. (Though ideally error handling would be better.)

**Comment by sanmadjack** [comment]
I agree, error handling would be better. If you check further up this thread, about 8 days ago, I committed a code change to allow better error handling for this.
